name: Build glslang

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["armeabi-v7a", "arm64-v8a"]
      fail-fast: false

    name: "Build glslang"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt -y install wget python3 python-is-python3 unzip zip

      - name: Build with script
        run: bash "${{matrix.arch}}.sh"

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: "glslang-${{matrix.arch}}"
          path: glslang/install/${{matrix.arch}}/*
