name: Build spirv-cross & glslang

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["armeabi-v7a", "arm64-v8a", "x86", "x86_64"]
      fail-fast: false

    name: "Build spirv-cross & glslang"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt -y install wget python3 python-is-python3 unzip zip git cmake

      - name: Build with script
        run: bash "${{matrix.arch}}.sh"

      - name: Upload spirv-cross build output
        uses: actions/upload-artifact@v4
        with:
          name: "spirv-cross-${{matrix.arch}}"
          path: SPIRV-Cross/install/${{matrix.arch}}/*

      - name: Upload glslang build output
        uses: actions/upload-artifact@v4
        with:
          name: "glslang-${{matrix.arch}}"
          path: glslang/install/${{matrix.arch}}/*
